### ISSUE TITLE
Error on Loadup

### ISSUE THREAD

**Issue by SoyGoy** [BetonQuest/BetonQuest-Editor#67]
java.lang.NullPointerException
    	at pl.betoncraft.betonquest.editor.persistence.PreviousState.<init>(PreviousState.java:61)
    	at pl.betoncraft.betonquest.editor.persistence.Persistence.<init>(Persistence.java:53)
    	at pl.betoncraft.betonquest.editor.BetonQuestEditor.start(BetonQuestEditor.java:96)
    	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
    	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
    	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    	at java.lang.Thread.run(Unknown Source)

**Comment by AllegorickBlock** [comment]
You have an error in you quest file
