### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by victoryneM** [BetonQuest/BetonQuest-Editor#74]
Hi, I can't open anymore my editor with this message, can you help me ?
___________

    java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    	at java.lang.String.substring(Unknown Source)
    	at pl.betoncraft.betonquest.editor.model.PackageSet.parseStreams(PackageSet.java:274)
    	at pl.betoncraft.betonquest.editor.model.PackageSet.loadFromDirectory(PackageSet.java:193)
    	at pl.betoncraft.betonquest.editor.BetonQuestEditor.loadPreviousData(BetonQuestEditor.java:151)
    	at pl.betoncraft.betonquest.editor.BetonQuestEditor.start(BetonQuestEditor.java:102)
    	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
    	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
    	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
    	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
    	at java.lang.Thread.run(Unknown Source)

**Comment by Wolf2323** [comment]
This was transferred to the BetonQuest-Editor repository. This is not directly related to BetonQuest
